** Usable
- [-] Tests for api
- [ ] Permission list/allow/deny lua api
- [ ] Fullscreen
- [ ] Zoom in/out
- [ ] Run JS in page (web.view.eval_js())
- [ ] Use table for all internals api options?
- [ ] Create window with new profile
- [ ] User data/profiles management

** Bugs
- [ ] INVESTIGATE: Check why urlchanged doesnt fire for first url open sometimes
- [ ] INVESTIGATE: Segfault on close sometimes
- [ ] API's don't validate types. (type conversion segfaults)

** Next
- [ ] Configuration validation
- [ ] web.win.* apis (list, current_id)
- [ ] Allow toggling devtools
- [ ] Tests for window
- [ ] More tests for stack
- [ ] Tests for router
- [ ] Set search text as the user is typing (dmenu -r)
- [ ] Log stdout, errors and results from lua somewhere
- [ ] Conflict in keymap (keymap already exists)
- [ ] Allow pattern filtering for event listeners
- [ ] Allow tab_id, win_id filtering for event listeners
- [ ] Handle resource cleanup + signal disconnecting
- [ ] Private window (in-memory profile)
- [ ] Read page contents via lua

** Later
- [ ] Bookmarking
- [ ] User scripts (greasemonkey?)
- [ ] User stylesheets (per site and global?)
- [ ] Support multiple modes for keymap.set: `web.keymap.set({'n','i'}, ...)`
- [ ] static linking for qt
- [X] vendor web.inspect with build
- [ ] Right click context menu items
- [ ] Listen to renderprocesstermination signal
- [ ] Create view with html (web.view.set_html())
- [ ] Change instance manager command format

** Later later
- [ ] Custom file picker
- [ ] remote debugging with cdp (spider-repl)

** Maybe
- [ ] Floating webviews?
- [ ] Move modal keymap management into lua?

** Notes
- view = 0, nil, none: Current view
- Win = 0: Current window
- Win = nil, none: All windows or current window based on operation
- Keep track of last focused window (current window is last focused)
#+begin_src lua
web.view.set_url(url) -- Set url for current view
web.view.set_url(url, { view = 1 }) -- Set url for view 1
web.view.set_url(url, { view = 1, win = 1 }) -- Set url for view 1 in win 1
web.view.set_url(url, { win = 1 }) -- Set url for current view in win 1

web.view.create(url, { win = 1 }) -- New view in win 1
web.view.create(url) -- New view in current window

web.view.close({ view = 1 }) -- Close view 1
web.view.close() -- Close current view in current window

web.view.list({ win = nil }) -- List all tabs
web.view.list({ win = 1 }) -- List win 1 tabs

web.view.select({ view = 1, win = 1 }) -- Select win 1 view
web.view.select({ view = 1, win = 0 }) -- Select view 1 in current window
web.view.select({ view = 1 }) -- Select view 1

web.view.current({ win = 1 }) -- Current view in win 1
web.view.current() -- Current view in current win

web.history.back(1) -- Back for current view in current window
web.history.back(1, { view = 1 }) -- Back for view 1
web.history.back(1, { win = 1 }) -- Back for current view in win 1

web.keymap.set('n', '<c-r>', ..., { view = 1 }) -- Set keymap for view 1
web.keymap.set('n', '<c-r>', ..., { win = 1 }) -- Set keymap for win 1
web.opt.new_tab_url = 'https://duckduckgo.com'

-- Search api
web.search.set_search_text('whatever')
web.search.next()
web.search.prev()
web.search.get_search_text()
web.search.current()
web.search.total()

web.decorations.configure('left', {
  url = 'https://something.com',
  size = 100,
})
local sidebar_decoration = web.decorations.left()
web.decorations.delete(sidebar_decoration)
web.decorations.hide(sidebar_decoration)

web.decorations.configure('top', { size = 28 })
local tabline_decoration = web.decorations.top()
web.view.set_html('<div>Hello world</div>', { view_id = tabline_decoration.view_id })
#+end_src
